services:
  backend:
    image: vault-backend
    container_name: vault-backend
    ports:
      - "8000:8000"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: always

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    container_name: filebeat
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - elasticsearch
      - kibana
    restart: always

  frontend:
    image: vault-frontend
    container_name: vault-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

  secops-bot:
    build: 
      context: ./secops-bot
      dockerfile: Dockerfile
    container_name: secops-bot
    restart: always
    env_file:
    - ./secops-bot/.env
    depends_on:
      - backend
      - elasticsearch