apiVersion: v1
kind: Secret
metadata:
  name: secops-bot-env
  namespace: devsecops-project
type: Opaque
stringData:
  TELEGRAM_TOKEN: "replace-me"
  TELEGRAM_CHAT_ID: "replace-me"
  OPENROUTER_API_KEY: "replace-me"
  GITLAB_URL: "https://gitlab.com"
  GITLAB_TOKEN: "replace-me"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secops-bot
  namespace: devsecops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secops-bot
  template:
    metadata:
      labels:
        app: secops-bot
    spec:
      containers:
        - name: secops-bot
          image: zero-trust-vault/secops-bot:semester
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: secops-bot-env
